# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem
from PyQt5.QtWidgets import QComboBox, QListView
from PyQt5.QtCore import Qt

class MultiSelectComboBox(QComboBox):
    def __init__(self, parent=None):
        super(MultiSelectComboBox, self).__init__(parent)
        self.view().pressed.connect(self.handleItemPressed)  # 连接项被按下的信号到 handleItemPressed 方法
        self._changed = False
        self.setView(QListView(self))  # 设置视图为 QListView

    def handleItemPressed(self, index):
        item = self.model().itemFromIndex(index)
        if item.checkState() == Qt.Checked:
            item.setCheckState(Qt.Unchecked)  # 如果已经选中，则取消选中
        else:
            item.setCheckState(Qt.Checked)  # 如果未选中，则选中
        self._changed = True

    def hidePopup(self):
        if not self._changed:
            super(MultiSelectComboBox, self).hidePopup()  # 如果没有改变，调用父类的 hidePopup 方法
        self._changed = False

    def setModel(self, model):
        super(MultiSelectComboBox, self).setModel(model)  # 调用父类的 setModel 方法
        for i in range(model.rowCount()):
            item = model.item(i)
            item.setFlags(Qt.ItemIsUserCheckable | Qt.ItemIsEnabled)  # 设置为可选并启用
            item.setCheckState(Qt.Unchecked)  # 初始化为未选中

    def checkedItems(self):
        items = []
        for i in range(self.model().rowCount()):
            item = self.model().item(i)
            if item.checkState() == Qt.Checked:
                items.append(item.text())  # 如果选中，添加到列表
        return items  # 返回所有被选中的项的文本
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(948, 569)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 951, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(770, 10, 121, 201))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_3)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_4)
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 721, 521))
        self.graphicsView.setObjectName("graphicsView")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(770, 320, 121, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(770, 240, 121, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMouseTracking(False)
        self.label.setTabletTracking(False)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.verticalLayout_15.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMouseTracking(False)
        self.label_2.setTabletTracking(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_15.addWidget(self.label_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_8 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_8.setGeometry(QtCore.QRect(770, 30, 121, 411))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")

        self.comboBox_17 = MultiSelectComboBox(self)  # 创建一个 MultiSelectComboBox 实例
        model = QStandardItemModel(self.comboBox_17)  # 创建一个 QStandardItemModel 实例
        items = [ "上包络线", "下包络线", "均值包络线"]  # 定义选项列表
        for item_text in items:
            item = QStandardItem(item_text)
            item.setFlags(Qt.ItemIsUserCheckable | Qt.ItemIsEnabled)  # 设置为可选并启用
            item.setData(Qt.Unchecked, Qt.CheckStateRole)  # 初始化为未选中
            model.appendRow(item)  # 将项添加到模型中
        self.comboBox_17.setModel(model)  # 设置模型到 comboBox
        self.comboBox_17.setObjectName("comboBox_17")
        self.verticalLayout_11.addWidget(self.comboBox_17)

        self.comboBox_18 = MultiSelectComboBox(self)  # 创建一个 MultiSelectComboBox 实例
        model = QStandardItemModel(self.comboBox_18)  # 创建一个 QStandardItemModel 实例
        items = ["线性拟合", "非线性拟合"]  # 定义选项列表
        for item_text in items:
            item = QStandardItem(item_text)
            item.setFlags(Qt.ItemIsUserCheckable | Qt.ItemIsEnabled)  # 设置为可选并启用
            item.setData(Qt.Unchecked, Qt.CheckStateRole)  # 初始化为未选中
            model.appendRow(item)  # 将项添加到模型中
        self.comboBox_18.setModel(model)  # 设置模型到 comboBox
        self.comboBox_18.setObjectName("comboBox_18")
        self.verticalLayout_11.addWidget(self.comboBox_18)

        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget_8)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_11.addWidget(self.pushButton_19)
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget_8)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_11.addWidget(self.pushButton_18)
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget_8)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_11.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget_8)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_11.addWidget(self.pushButton_21)
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_6.setGeometry(QtCore.QRect(10, 10, 721, 521))
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.layoutWidget_9 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_9.setGeometry(QtCore.QRect(770, 440, 121, 81))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_30 = QtWidgets.QPushButton(self.layoutWidget_9)
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_12.addWidget(self.pushButton_30)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget_9)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_12.addWidget(self.pushButton_15)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_7.setGeometry(QtCore.QRect(10, 10, 721, 521))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.layoutWidget_11 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_11.setGeometry(QtCore.QRect(770, 340, 121, 151))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_26 = QtWidgets.QPushButton(self.layoutWidget_11)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_14.addWidget(self.pushButton_26)
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_22.setGeometry(QtCore.QRect(740, 20, 81, 31))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_23.setGeometry(QtCore.QRect(740, 60, 81, 31))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_24.setGeometry(QtCore.QRect(740, 100, 81, 31))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_25.setGeometry(QtCore.QRect(740, 142, 81, 31))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_27.setGeometry(QtCore.QRect(740, 182, 81, 31))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_28.setGeometry(QtCore.QRect(740, 222, 81, 31))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_29.setGeometry(QtCore.QRect(740, 260, 81, 31))
        self.pushButton_29.setObjectName("pushButton_29")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(830, 20, 81, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_2.setGeometry(QtCore.QRect(830, 60, 81, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_3.setGeometry(QtCore.QRect(830, 100, 81, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_4.setGeometry(QtCore.QRect(830, 140, 81, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_5.setGeometry(QtCore.QRect(830, 180, 81, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_6.setGeometry(QtCore.QRect(830, 220, 81, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_7.setGeometry(QtCore.QRect(830, 260, 81, 31))
        self.textEdit_7.setObjectName("textEdit_7")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "数据获取"))
        self.comboBox.setItemText(1, _translate("Form", "读取图像"))
        self.comboBox.setItemText(2, _translate("Form", "读取文件"))
        self.comboBox.setItemText(3, _translate("Form", "手动输入"))
        self.comboBox.setItemText(4, _translate("Form", "现有函数"))
        self.comboBox_2.setItemText(0, _translate("Form", "维度方向"))
        self.comboBox_2.setItemText(1, _translate("Form", "横向"))
        self.comboBox_2.setItemText(2, _translate("Form", "纵向"))
        self.comboBox_3.setItemText(0, _translate("Form", "x轴"))
        self.comboBox_3.setItemText(1, _translate("Form", "维度1"))
        self.comboBox_3.setItemText(2, _translate("Form", "维度2"))
        self.comboBox_4.setItemText(0, _translate("Form", "y轴"))
        self.comboBox_4.setItemText(1, _translate("Form", "维度1"))
        self.comboBox_4.setItemText(2, _translate("Form", "维度2"))
        self.pushButton_2.setText(_translate("Form", "缓存数据"))
        self.pushButton_3.setText(_translate("Form", "绘制曲线"))
        self.pushButton.setText(_translate("Form", "保存图像"))
        self.label.setText(_translate("Form", "x轴维度名称"))
        self.label_2.setText(_translate("Form", "y轴维度名称"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "数据生成"))


        self.pushButton_19.setText(_translate("Form", "傅里叶变换"))
        self.pushButton_18.setText(_translate("Form", "频谱"))
        self.pushButton_20.setText(_translate("Form", "PCA"))
        self.pushButton_21.setText(_translate("Form", "混合高斯拟合"))
        self.pushButton_30.setText(_translate("Form", "绘制曲线"))
        self.pushButton_15.setText(_translate("Form", "保存图像"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "数据处理"))
        self.pushButton_26.setText(_translate("Form", "保存图像"))
        self.pushButton_22.setText(_translate("Form", "横向拉伸倍数"))
        self.pushButton_23.setText(_translate("Form", "横向平移距离"))
        self.pushButton_24.setText(_translate("Form", "纵向拉伸倍数"))
        self.pushButton_25.setText(_translate("Form", "纵向平移距离"))
        self.pushButton_27.setText(_translate("Form", "横向拉伸倍数"))
        self.pushButton_28.setText(_translate("Form", "横向分割数量"))
        self.pushButton_29.setText(_translate("Form", "纵向分割数量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "曲线处理"))
